### ISSUE TITLE
doesn't build on 6.9 kernel 

### ISSUE THREAD

**Issue by MRSS02** [BoukeHaarsma23/zenergy#7]
Zenergy lo longer works on linux 6.9 mainline build, while it was working at 6.8. 

So I tried to investigate why and decided to compile the module manually, as I was previously installing it from AUR. 
But when trying to build this module in linux 6.9, it gives the following error:

```
/home/mparagames/zenergy/zenergy.c:229:27: error: ‘struct cpuinfo_x86’ has no member named ‘x86_max_cores’
  229 |         sockets = cpus / c->x86_max_cores;
      |
```

As it can be seen in this image:

![image](https://github.com/BoukeHaarsma23/zenergy/assets/68190118/e40fedfc-6ea5-4845-9845-2fe121083fcc)

However, apparently linux 6.9 changed the way information about the amount of physical cores, threads (logical cores), and dies per socket is obtained, according to this changelog on the documentation:

![image](https://github.com/BoukeHaarsma23/zenergy/assets/68190118/7549fd10-2ce6-4a10-b9c8-10d5b71e55cc)

So I tried changing line 229 of the code to 

```
sockets = cpus / topology_num_cores_per_package();`
```

Replacing `c->x86_max_cores to topology_num_cores_per_package()` with `topology_num_cores_per_package()`.

This will make it compile on linux 6.9, but i assume it would then fail on linux 6.8 and below (I haven't tested it, however).

![image](https://github.com/BoukeHaarsma23/zenergy/assets/68190118/69fbf2a0-891c-4a1d-98c8-9caf2102c942)

Please keep in mind, however, that I am no kernel or kernel module developer, I am just a cs student and I only know very basic c and code some projects as a hobby (usually in high level languages). Therefore, please be aware that I am prone to mistakes, as I don't really know what exactly would be the side effects of this change. 
So i just kindly ask that you look deeper at what caused the change in linux 6.9 that made zenergy stop working, and I am giving this as a possible hint of what could be going on from what I observed. 

Thank you in advance.
